import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const CreatePostWizard: NextPage = () => {
  const { user } = useUser();
  if (!user) {
    return null;
  }

  return (
    <div className=" flex w-full gap-3 border-b border-slate-400 p-2">
      <img
        src={user.profileImageUrl}
        alt="Profile image"
        className="h-14 w-14 rounded-full"
      />
      <input
        type="text"
        placeholder="What's on your mind?"
        className="grow rounded-full  bg-transparent p-2 outline-none"
      />
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser(); //esto viene de @clerk/nextjs

  const { data, isLoading } = api.posts.getAll.useQuery();
  if (isLoading) {
    return <div>Loading...</div>;
  }
  if (!data) {
    return <div>Something went wrong</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center ">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          {!user.isSignedIn && (
            <div className="flex justify-center border-b border-slate-400 p-4 text-white">
              <SignInButton mode="modal">
                <button className="btn text-white">Sign in</button>
              </SignInButton>
              <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
            </div>
          )}
          {user.isSignedIn && <CreatePostWizard />}

          <div className="flex flex-col">
            {[...data, ...data]?.map((post) => (
              <div
                key={post.id}
                className="border-b border-slate-400 p-8 text-white"
              >
                <Link href={`/posts/${post.id}`}></Link>
                <p>{post.content}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
