import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser(); //esto viene de @clerk/nextjs

  const data = api.posts.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!user.isSignedIn && (
          <>
            <SignInButton mode="modal">
              <button className="btn text-white">Sign in</button>
            </SignInButton>
            <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
          </>
        )}
        {!!user.isSignedIn && <SignOutButton />}

        <div>
          {data.data?.map((post) => (
            <div key={post.id} className="text-white">
              <Link href={`/posts/${post.id}`}></Link>
              <p>{post.content}</p>
              <p>{post.createdAt.toTimeString()}</p>

              <p>{post.authorId}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
